---
# tasks file for vim-ide

- name: Include Vim-specific variables
  include_vars: "{{ vim_package }}.yml"

- name: Include os family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: set_fact vim_all_packages
  set_fact:
    vim_packages_all: "{{ vim_packages_all + [item] }}"
  with_items:
    - "{{vim_package}}"
    - "{{vim_extra_package}}"
    - git
    - socat

- name: Apply all vim packages
  package:
    name: "{{vim_packages_all}}"
    state: present

- name: Apply python3 neovim dependency
  pip:
    name: pynvim
    executable: pip3

- name: Ensure main dir for vim is set
  lineinfile:
    path: /etc/profile.d/vim.sh
    line: export EDITOR="{{ editor }}"
    create: true

- include_tasks: configure_vim.yml
  vars:
    user: "{{ vim_user }}"
  with_items: "{{ vim_users }}"
  loop_control:
    loop_var: vim_user

- include_tasks: global_vim.yml
