---
# tasks file for vim-ide

- name: Include Vim-speciic variables
  include_vars: "{{ vim_package }}.yml"

- name: Include os family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure (neo)vim packages
  package:
    name: ["{{ vim_package }}", "{{ vim_python_package }}", psutils, socat, python-pip, git]
    state: present

- name: Ensure main dir for vim is set
  lineinfile:
    path: /etc/profile.d/vim.sh
    line: export EDITOR="{{ editor }}"
    create: true

- include_tasks: configure_vim.yml
  vars:
    user: "{{ vim_user }}"
  with_items: "{{ vim_users }}"
  loop_control:
    loop_var: vim_user

- include_tasks: global_vim.yml
  
