---
# tasks file for vim-ide

#- name: declare vars
#  vars:
#    vim_packages_all: []

- name: Include Vim-specific variables
  include_vars: "{{ vim_package }}.yml"

- name: Include os family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: All vim packages
  set_fact:
    vim_packages_all: "{{ vim_packages_all + [item] }}"
  with_items:
    - "{{vim_package}}"
    - "{{vim_extra_package}}"
    - git
    - psutils
    - python-pip
    - socat

- name: Ensure (neo)vim packages
  package:
    name: "{{vim_packages_all}}"
    state: present

- name: Ensure main dir for vim is set
  lineinfile:
    path: /etc/profile.d/vim.sh
    line: export EDITOR="{{ editor }}"
    create: true

- include_tasks: configure_vim.yml
  vars:
    user: "{{ vim_user }}"
  with_items: "{{ vim_users }}"
  loop_control:
    loop_var: vim_user

- include_tasks: global_vim.yml
