---
- import_playbook: playbooks/admin-workstation.yml
- import_playbook: playbooks/apply-vim.yml
- import_playbook: playbooks/apply-zsh.yml
- import_playbook: playbooks/btrfs-backup-srv.yml
- import_playbook: playbooks/docker-srv.yml
- import_playbook: playbooks/docker-workstation.yml
- import_playbook: playbooks/vagrant.yml
