---

# tasks file for desktop

- include_vars: "{{ ansible_os_family }}.yml"

- name: check if cd device /dev/sr0 exists
  stat:
    path: /dev/sr0
  register: sr0_status

  # If Bluetooth kernel module is found, install the necessary packages.
  # This is done in the desktop role because I never installed bluetooth utilities on a headless system.
- name: check for loaded bluetooth kernel module
  command: modinfo bluetooth
  register: modinfo_bluetooth
  ignore_errors: true
  # 0: Bluetooth kernel Module found / 1: No bluetooth kernel moudle found

- name: apply bluetooth stuff
  include_tasks: bluetooth.yml
  when: modinfo_bluetooth.rc == 0

- name: apply xorg if wanted
  include_tasks: xorg.yml
  when: '"xorg" in display_backend'

- name: apply plasma desktop if wanted
  include_tasks: plasma.yml
  when: '"plasma" in desktop_system'

  # I apply the network manager in the desktop role because I never use it on non desktop systems
- name: apply networkmanager
  include_tasks: networkmanager.yml

- name: apply sddm display manager if wanted
  include_tasks: sddm.yml
  when: '"sddm" in display_manager'

- name: apply cd-utils
  include_tasks: cdutils.yml
  when: sr0_status.stat.isreg is defined

- name: apply desktop applications
  include_tasks: applications.yml
