---

- name: apply sddm package
  package:
    name: sddm

- name: apply sddm contol center package
  package:
    name: sddm-kcm
  when: '"plasma" in desktop_system'

  # Ansible thinks that this operation fails even when it works
- name: ensure sddm service is started and running
  service:
    name: sddm
    state: started
    enabled: true
