---

- name: apply sddm package
  package:
    name: sddm

- name: apply sddm contol center package
  package:
    name: sddm-kcm
  when: '"plasma" in desktop_system'

- name: ensure sddm service is started and running
  service:
    name: sddm
    state: stopped
    enabled: false
