---

- include_vars: "{{ ansible_os_family }}.yml"

- name: check for graphic device
  shell:
    cmd: lspci | grep VGA
  register: graphic_device

- name: ensure general xorg packages
  package:
    name: "{{ xorg_packages_general }}"

- name: debug graphics
  debug:
    msg: "{{ graphic_device.stdout }}"


- name: install virtualbox graphics
  package:
    name: "{{ virtualbox_xorg_support }}"
  when: ansible_virtualization_type == "virtualbox"
