---
# tasks file for devop

- include_vars: "{{ ansible_os_family }}.yml"

- name: define list of general dev packages
  set_fact:
    general_dev_packages: [dnsmasq]


- name: Ensure operations packages for all distributions
  package:
    name: "{{ general_packages }} + {{distro_specific_admin_packages}}"
    state: present

- name: Ensure developer pakages
  package:
    name: "{{ general_packages }} + {{ distro_specific_dev_packages }}"
    state: present
