---
### For now dummy file for Archlinux specific tasks


- name: Apply yay dependencies
  package:
    name: [git, base-devel, xz, shellcheck]
    state: latest

- name: clone yay (AUR management)
  command: git clone https://github.com/Jguer/yay.git  
  args:
    creates: yay
  become: false
  become_user: "{{ ansible_user }}"

- name: install yay (AUR management)
  command: makepkg -si --noconfirm
  args:
    chdir: yay
    creates: /usr/bin/yay
  become: false
  become_user: "{{ ansible_user }}"
