---
### Debian specific tasks

- name: Enable Buter extra repsitories
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - "deb http://deb.debian.org/debian buster contrib non-free"
    - "deb http://deb.debian.org/debian buster-backports contrib non-free"
    - "deb http://deb.debian.org/debian buster-updates contrib non-free"
    - "deb http://deb.debian.org/debian-security/ buster/updates contrib non-free"
  when: ansible_architecture == "x86_64"
  # These Packages are not available for RasperryPI OS

- name: install virtualbox-iso-package
  package:
    name: virtualbox-guest-additions-iso
    state: latest
  when: ansible_virtualization_type == "virtualbox" and ansible_architecture == "x86_64"
