---
# tasks file for common

- name: Register number of modules for virtualisation
        # This is later used to determine if we are on a virtualized plattform
  shell:
    cmd: lsmod | grep -e vbox -e virtio -e vmware | wc -l
  register: virt_modules

- include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "{{ ansible_os_family }}.yml"

# Incluse task for managing users
- include_tasks: users.yml
- include_tasks: packages.yml
- include_tasks: proxy.yml
- include_tasks: sleepy_disks.yml

- name: Install common packages for all plattforms
  package:
    name: [acl, at, bash-completion, gdisk, git]
    state: present
    # acl can be necessary for become_user and getting privileges for temp file in vim role

- name: Enable fstrim timer
  service:
    name: fstrim.timer
    state: started
    enabled: true

### Fehlert gerade rum, grund nicht nachvollziehbar
#- name: Setup locale
#  locale_gen:
#    name: "{{ default_locale }}"
#    state: present


- name: Ensure Timezone
  timezone:
    name: "{{ timezone }}"
