---

- name: Apply hdparm.service file
        # if disks shold be send to sleep
  template:
    src: hdparm.j2
    dest: /etc/systemd/system/hdparm.service
  notify: hdparm_restart
  when: sleepy_disks is defined

- name: Remove hdparm.service file if no sleepy_disks defined
  file:
    path:  /etc/systemd/system/hdparm.service
    state: absent
  when: sleepy_disks is undefined


- name: register if hdparm.service exists
  stat:
    path: /etc/systemd/system/hdparm.service
  register: hdparm_exists


- name: Disable hdparm.service
  service:
    name: hdparm
    state: stopped
    enabled: false
  when: sleepy_disks is undefined and hdparm_exists.stat.exists == true












