---
# handlers file for privoxy

- name: privoxy_restart
  service:
    daemon_reload: true
    enabled: true
    name: privoxy
    state: restarted

- name: privoxy-blocklist_reload
  service:
    daemon_reload: true
