---

- hosts: localhost
  connection: local
  become: true
  vars:
    port_packages:
      - cargo
      - docker
      - docker-compose
      - gnupg2
      - helm-3.7
      - kind
      - kubectx
      - libvirt
      - macfuse
      - neovim
      - nmap
      - nodejs14
      - p7zip
      - pam-reattach
      - py39-pip
      - python39
      - rsync
      - tmux
      - virt-manager
      - watch
      - wget
      - zsh
    pip_packages:
      - ansible
      - ansible-lint
      - openshift
      - pynvim
      - PyYaml # dependency for Ansible

# pam-reattach: enables touch-id in tmux sessions
# cargo: rust package manager. needed for LunarVim

  tasks:
  - name: Install macports packages
    community.general.macports:
      name: "{{ item }}"
    with_items: "{{ port_packages }}"


  - name: Install pip packages
    pip:
      name: "{{ item }}"
    become: false
    with_items: "{{ pip_packages }}"
