---

# sudo port select --set helm helm3.7
#
- hosts: localhost
  connection: local
  become: true
  vars:
    port_packages:
      - bitwarden-cli
      - docker
      - docker-compose
      - gnupg2
      - helm-3.7
      - kind
      - libvirt
      - macfuse
      - neovim
      - nmap
      - nodejs14
      - py39-pip
      - py39-xattr
      - python39
      - rsync
      - virt-manager
      - watch
      - wget
      - zsh
    pip_packages:
      - ansible
      - ansible-lint
      - openshift
      - pynvim
      #- bitwarden-simple-cli # needed for Ansble Bitwarden module
      - PyYaml # dependency for Ansible

# py39-xattr: for opencore / munki installer

  tasks:
  - name: Install macports packages
    community.general.macports:
      name: "{{ item }}"
    with_items: "{{ port_packages }}"


  - name: Install pip packages
    pip:
      name: "{{ item }}"
    become: false
    with_items: "{{ pip_packages }}"
