---
- hosts: localhost
  connection: local
  become: true
  vars:
    port_packages:
      - bitwarden-cli
      - docker
      - docker-compose
      - gnupg2
      - helm-3.6
      - kind
      - libvirt
      - neovim
      - nmap
      - py38-pip
      - python38
      - virt-manager
      - zsh
    pip_packages:
      - ansible
      - ansible-lint
      - pynvim
      - bitwarden-simple-cli # needed for Ansble Bitwarden module
      - PyYaml # dependency for Ansible


  tasks:
  - name: Install macports packages
    community.general.macports:
      name: "{{ item }}"
    with_items: "{{ port_packages }}"


  - name: Install pip packages
    pip:
      name: "{{ item }}"
    become: false
    with_items: "{{ pip_packages }}"
