---

## Creates users und publishes public keys

- name: Manage users
  hosts: all
  become: true

  tasks:
  - name: manage users
    user:
      name: "{{ item.username }}"
      comment: "{{ item.fullname }}"
      create_home: true
      shell: /bin/bash
    with_items: "{{users}}"

  - name: Ensure public_keys
    authorized_key: user={{ item.username }}
      key="{{ lookup('file', '../files/public_keys/{{ item.username }}.pub') }}"
    with_items: "{{users}}"
