---

- name: Docker setup
  hosts: docker_hosts
  become: true

  tasks:

  - name: Install packages to allow apt to use a repository over HTTPS
    package:
      name: [ apt-transport-https, ca-certificates, curl, gnupg2, software-properties-common ]
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Add Dockers official GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
    when: ansible_facts['os_family'] == "Debian"

  - name: Add Debian 10 apt repository
    apt_repository:
      repo: deb https://download.docker.com/linux/debian buster stable
      state: present
    when: ansible_facts['os_family'] == "Debian"


  - name: Ensure Docker package
    package:
      name: [ docker-ce ]
      state: present

  - name: Ensure docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Ensure docker data directory
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /mnt/docker
      - /mnt/workspace

  - name: Ensure docker@.service file
    copy:
      src: docker@.service
      dest: /etc/systemd/system/docker@.service
      owner: root
      group: root
      mode: '0644'

  - name: Enable and start Docker
    service:
      name: docker
      state: started
      enabled: yes
      daemon_reload: true
